### ISSUE TITLE
Is it possible change barman log format?

### ISSUE THREAD

**Issue by dawncold** [EnterpriseDB/barman#184]
I want barman records json format log, so I change barman's log format.

I found barman could read `log_format` from config file: https://github.com/2ndquadrant-it/barman/blob/master/barman/config.py#L628, but I can't override default log format in config file.

I set `log_format` in `/etc/barman.conf`:
```
[barman]
...
log_level = INFO
log_format = %(message)s
```

when I use barman cli, it raised an exception:
```
EXCEPTION: Bad value substitution:
	section: [barman]
	option : log_format
	key    : message
	rawval : %(message)s

See log file for more details.
No handlers could be found for logger "barman.cli"
```
I think that's something wrong with `ConfigParser`

**Comment by amenonsen** [comment]
This still doesn't work, and looks like a bug. I'll leave this open for now.

**Comment by amenonsen** [comment]
I'm closing this old issue now because (a) just setting `log_format`, even if it worked, wouldn't be enough for safe JSON output, and (b) I'm not particularly interested in allowing log_format to be customised to this degree—it's a pretty niche use case, and even if we were to support different log formats, we would do it with a single keyword like `combined` (obviously that is a web server log format, not applicable to Barman; just an example of what I mean).
