### ISSUE TITLE
network failure tolerance : making barman not FATAL

### ISSUE THREAD

**Issue by achix** [EnterpriseDB/barman#192]
If using streaming replication for WALs then replication slots are mandatory by barman. This means that a network disruption would mean that WALs accumulate for the replication slot, disk space fills up, and eventually the death of the primary or the secondary.
If using archive_command then similarly repeated failures to archive the WALs would mean indefinite accumulation of the files, and eventually the death of the primary.

So, what are critical features IMHO : 
1) ability to stream without replication slots. Losing the backup continuity is better than losing the production DB
2) a way similar to pgbackrest archive-push --archive-push-queue-max . Which means if WAL files accumulated for archiving gets large enough that it indicates a problem, then pretend that it suceeds and make room for postgresql to survive.

**Comment by jeffjanes** [comment]
It is possible to use the WAL streaming without a slot if you set "archiver=on".  You don't actually need the server to have an archiver configured, you just need to tell barman that it does.  This doesn't seem to be documented anywhere other than in the commit message which introduced slots, ed3ae6b97a5108.  This behavior is certainly not intuitive.  The docs do tell you what might happen if you run without slots, but do not tell you how to do it.

Running this way is also not very well supported.  If you loss sync during a backup because wal_keep_segments was exceeded, the backup will continue to be listed as "WAITING_FOR_WALS" rather than "FAILED" for a long time, at least until you manually reset the WAL archive and get streaming running again.  And once that is resolved, there is no indication with "check" or with "list-backup" that there is a hole in your WAL stream.  You would need to keep track of that manually.

**Comment by amenonsen** [comment]
If streaming or archiving fails for such a long time that the primary runs out of disk space and dies, I think the real problem is that nobody noticed the problem earlier, not that Barman requires a replication slot. What if it had been log files (say), and not WAL, that were filling up the disk? Maybe there are good reasons to want to stream without a replication slot (and we'll consider them), but "it might stop working someday" is not the most compelling one.

Streaming without a slot but with `archiver=on` is certainly not intended behaviour, so I'm not surprised it's not well-supported. However, we do plan to add better tracking of continuity of the WAL archive in various scenarios.

Likewise, I'm not interested in adding a feature to pretend that WAL files are being archived when they are not.

**Comment by amenonsen** [comment]
By the way, this new feature in Postgres 13 may be interesting:

```
commit c6550776394e25c1620bc8258427c8f1d448080d
Author: Alvaro Herrera <alvherre@alvh.no-ip.org>
Date:   Tue Apr 7 18:35:00 2020 -0400

    Allow users to limit storage reserved by replication slots

    Replication slots are useful to retain data that may be needed by a
    replication system.  But experience has shown that allowing them to
    retain excessive data can lead to the primary failing because of running
    out of space.  This new feature allows the user to configure a maximum
    amount of space to be reserved using the new option
    max_slot_wal_keep_size.  Slots that overrun that space are invalidated
    at checkpoint time, enabling the storage to be released.

    Author: Kyotaro HORIGUCHI <horiguchi.kyotaro@lab.ntt.co.jp>
    Reviewed-by: Masahiko Sawada <sawada.mshk@gmail.com>
    Reviewed-by: Jehan-Guillaume de Rorthais <jgdr@dalibo.com>
    Reviewed-by: Álvaro Herrera <alvherre@alvh.no-ip.org>
    Discussion: https://postgr.es/m/20170228.122736.123383594.horiguchi.kyotaro@lab.ntt.co.jp
```
