### ISSUE TITLE
Exclude /log/ as well as /pg_log/

### ISSUE THREAD

**Issue by jeffjanes** [EnterpriseDB/barman#207]
The backup currently excludes /pg_log/*  (backup_executor.py line 989), which is the default location for human-readable server log files in versions before 10.  But it does not also exclude the /log/*, which is spelling for that default location in versions 10 and up.  Is this an oversight, or is there a reason you don't want to exclude those files?  (In which case, it probably deserves a code comment)

**Comment by L-Bd** [comment]
Is there any update on this issue at all from 2nd Quadrant?
We're belatedly moving our clusters up to version 11 from 9.x and suddenly noticed the log files being picked up by barman.
Given that `log_directory` is configurable, having barman read that value to exclude all logs (if that is the intention) would be the best outcome. But otherwise is there a reason why `/log/*' isn't among the default list of exclusions?

**Comment by amenonsen** [comment]
I've added /log/* to the default exclusions. This will be in the next Barman release.
