### ISSUE TITLE
"archiver" option default value seems to be "false" when streaming_archiver = on - documentation does not mention this

### ISSUE THREAD

**Issue by loop-evgeny** [EnterpriseDB/barman#280]
https://docs.pgbarman.org/release/2.10/barman.5.html says that the default value of the "archiver" option is true". However, it appears to be false. I did not set this option in my barman 2.10 installation and got an error from barman check:

```
# barman check settings
Server settings:
	empty incoming directory: FAILED ('/backup/barman/settings/incoming' must be empty when archiver=off)

# barman show-server settings |grep archiver
	archiver: False
```

Explicitly setting `archiver = true` in barman.conf fixed this.

I have `streaming_archiver = on`, which seems to automatically sets `archiver = false`. (If I comment that out then archiver is true by default.)

**Comment by mikewallace1979** [comment]
Thanks for raising this @loop-evgeny.

There is some wider context here which is that the default value of the `archiver` option was changed from True to False in Barman 2 however [some code was added to preserve backwardly compatible behaviour](https://github.com/EnterpriseDB/barman/blob/8656d01bc82bfafff7f417ff7e3aa43c82b33a04/barman/server.py#L346-L357) which will set `archiver = True` if neither `archiver` nor `streaming_archiver` are set. Looking at the [commit which added this](https://github.com/EnterpriseDB/barman/commit/956b05bcf078ccb4f59d36130211823aeb07678c) the intention was to help migrations from Barman 1 to Barman 2.

I think to resolve this issue we should clarify the documentation so that it matches the current behaviour and also warns things will change in the next major version release (where it will be required that Barman users explicitly enable an archive mode).

**Comment by VGerris** [comment]
It would be a great improvement if the streaming template files in /etc/barman.d/ in the ubuntu ( and I guess other ) package could be update to have the option added, because currently the templates don't work as is without it. I use the latest barman shipped with Ubuntu 22.04 at the moment. Cool product ! thank you

**Comment by mikewallace1979** [comment]
Thanks for the feedback @VGerris.

The [current template](https://github.com/EnterpriseDB/barman/blob/a6939e2e77fec3bdd416faaa3e637fa5f6dae90d/doc/barman.d/streaming-server.conf-template) specifies just `streaming_archiver = on` - are you asking that `archiver = on` be added to that template?

**Comment by VGerris** [comment]
Hi,

Thank you for the link and reply.
Yes, I think it's a good idea to add it, it will not work otherwise.
Perhaps a comment stating default is false helps even more.
The reason I'm asking is because I put up everything according
documentation for streaming and then found this setting is needed on a the
GitHub comment. I can imagine nobody thought about it or complaint after
the change of the default?

Thank you and regards,
Vincent

**Comment by mikewallace1979** [comment]
@VGerris did you also have `archive_command` enabled in your PostgreSQL configuration? Normally `streaming_archiver = on` should be enough on its own, assuming only WAL streaming is required and `archive_command` is not configured. 

The "empty incoming directory" check will only fail if there are WAL files in the `incoming` directory *and* `archiver = on` is not set - in such cases the error can be resolved either by enabling `archiver = on` (if `archive_command` and WAL streaming are both to be used) or by disabling `archive_command` in PostgreSQL and removing the WALs from the `incoming` directory (if only WAL streaming is to be used).

Because `archiver = on` is only required with `streaming_archiver = on` when WALs are also being archived into the `incoming` directory via `archive_command`, I am thinking of adding the following to the template, rather than setting `archiver = on`:

```ini
; Uncomment the following line if you are also using archive_command
; otherwise the "empty incoming directory" check will fail
;archiver = on
```

What do you think?

**Comment by VGerris** [comment]
sorry for the late reply, I think that is good , especially when you add your explanation. I have to re-read the docs to understand if I have it setup properly now ( using streaming WAL archiving ). Thank you!
