### ISSUE TITLE
Streaming replication from primary, while using backup from standby (with replication slot)

### ISSUE THREAD

**Issue by thoro** [EnterpriseDB/barman#290]
Hi,

I'm using barman with a standby server to create the backups from, and I would like to use streaming replication from master

I read in the documentation that it's not supported, but I believe it's possible to to work around the issue, by using the streaming conn info to retrieve the replication slot info.

Currently before the pg_receivewal command is executed, the replication slot is checked, since conninfo and rsync point to the standby, the replication slot is unavailable and the receivewal never start due to the error:  

```
ERROR: ArchiverFailure:replication slot 'barman_streaming_replication' doesn't exist. Please execute 'barman receive-wal --create-slot db'
```

The check happens here: https://github.com/2ndquadrant-it/barman/blob/a577cb3da8dd178ff6f6dc56bf8cdde3b1296e91/barman/wal_archiver.py#L720 and uses the info from the standby, but should use the info from the streaming conninfo

**Comment by martinmarques** [comment]
This has been fixed in 3.10. See [de08a70](https://github.com/EnterpriseDB/barman/pull/868/commits/de08a703c2bad92deb35bb1d302fa379425bf714). We provide in that commit a `wal_streaming_conninfo` and a `wal_conninfo` to split the connection to the server we are backing up from the one where we stream WALs from.

I recommend also looking at the model feature we implemented in 3.10. I believe it will be of great use for you
