### ISSUE TITLE
target-tli should allow "current" or "latest" in addition to positive integer

### ISSUE THREAD

**Issue by kapouer** [EnterpriseDB/barman#305]
https://github.com/2ndquadrant-it/barman/blob/1bcdd6bcbaed9bd0b5882bc9543036e967ff3368/barman/cli.py#L339
defines target-tli as a positive integer but it can also be 'current' or 'latest' (which is the default value).
See [postgresql doc](https://www.postgresql.org/docs/13/runtime-config-wal.html#GUC-RECOVERY-TARGET-TIMELINE).

**Comment by amenonsen** [comment]
True. I'm putting this in the next milestone.

**Comment by mikewallace1979** [comment]
There are a few implementation details we need to think about here because barman uses `--target-tli` for more things than just setting the value of `recovery_target_timeline` in the PostgreSQL config.

Here are the places we're currently using the `--target-tli` option:

1. [Setting recovery_target_timeline in the postgres config](https://github.com/EnterpriseDB/barman/blob/8656d01bc82bfafff7f417ff7e3aa43c82b33a04/barman/recovery_executor.py#L1047-L1048) <-- Allowing `current` or `latest` is fine because we're just setting them to supported values.
2. [Getting the necessary WAL files](https://github.com/EnterpriseDB/barman/blob/8656d01bc82bfafff7f417ff7e3aa43c82b33a04/barman/recovery_executor.py#L268-L272) <-- [server.Server.get_required_xlog_files is assuming target_tli is numeric](https://github.com/EnterpriseDB/barman/blob/8656d01bc82bfafff7f417ff7e3aa43c82b33a04/barman/server.py#L1456). We can add some logic here to handle `current` (since this will be the same timeline as the backup, which we actually set as a default anyway if target_tli is not provided). We should also be able to handle `latest` here too though we'll need to find the most recent timeline in the xlogdb (there may be code which does this already).
3. [Setting PITR targets](https://github.com/EnterpriseDB/barman/blob/8656d01bc82bfafff7f417ff7e3aa43c82b33a04/barman/recovery_executor.py#L183-L195) <-- Here we have a [check to see if the destination timeline is different to that of the backup](https://github.com/EnterpriseDB/barman/blob/8656d01bc82bfafff7f417ff7e3aa43c82b33a04/barman/recovery_executor.py#L462) which will need re-writing to handle `current` and `latest`. Also a similar check [here](https://github.com/EnterpriseDB/barman/blob/8656d01bc82bfafff7f417ff7e3aa43c82b33a04/barman/recovery_executor.py#L505). I don't see any other uses here - the derived `d_tli` gets assigned to the `targets` dict however that only appears to be used for [writing output](https://github.com/EnterpriseDB/barman/blob/8656d01bc82bfafff7f417ff7e3aa43c82b33a04/barman/recovery_executor.py#L536-L539). As a side-note I wonder if logging the actual value of `target_tli` would be more appropriate there.

I don't see anywhere else in the codebase we're using the value of `--target-tli`.

So I think we have two choices in terms of implementation - either using handling `current` and `latest` where necessary in points 2 and 3 above, or resolving `current` or `latest` to an actual timeline somewhere before the code which actually uses it.
