### ISSUE TITLE
psycopg2 requirements

### ISSUE THREAD

**Issue by freddy34** [EnterpriseDB/barman#336]
Chance to use directly psycopg2-binary instead of psycopg2 as dependency requirement?

**Comment by amenonsen** [comment]
I guess you mean you want to `pip install psycopg2-binary` and use it with barman, instead of installing the OS psycopg2 package? You can do this if you also install Barman from pypi. Barman itself doesn't care where psycopg2 comes from, only that it is present. But we cannot declare optional dependencies in the rpm/deb packages, so it's not possible there.
