### ISSUE TITLE
How to stop retention from deleting a specific backup? 

### ISSUE THREAD

**Issue by mbartlomiejczyk** [EnterpriseDB/barman#370]
Let's say that retention is configured to purge back-ups older than 30 days. There's one critical from 10 days back which needs to be kept intact even after those 30 days (1 day before and 1 day after may be dropped).

**Comment by amenonsen** [comment]
This is currently not possible, but we are considering a `barman keep` command to address this (common) need.

**Comment by mikewallace1979** [comment]
Here's a sketch of the high-level implementation:

1. Add a `barman keep ${SERVER} ${BACKUP_ID}` command which adds a keep file at `${SERVER}/base/${BACKUP_ID}/annotations/keep`
2. Add a command for removing the keep file, either `barman keep --release` or perhaps a `barman nokeep` command
3. Update the behaviour of barman as follows:
  a. Delete by retention policy does not delete keep-annotated backups which are out of policy
  b. Delete by backup ID refuses to delete keep-annotated backups and prints a warning (“Remove the keep and try again”)
  c. WAL cleanup does not preserve WALs for keep-annotated backups forever - at some point they still need to get cleaned up because a `keep` backup cannot be expected to be used to recover to any point in time forever.

This should be implemented for both `barman` and `barman-cloud`.

**Comment by mikewallace1979** [comment]
work-in-progress implementation of most of the above can be found at https://github.com/EnterpriseDB/barman/compare/370-add-barman-keep-wip - hopefully the general approach makes sense in terms of minimizing duplication between barman and barman-cloud.

The big missing bit is WAL cleanup - having read the original notes for `barman keep` (thanks @gbartolini!), the way to implement this is to include information about the intended recovery target for the kept backup. So, the `keep` file would contain information about the target. A value of `standalone` would mean only keep the WALs necessary to ensure backup consistency, `full` would mean keeping all the WALs between the start of the base backup and the end of the log / start of the next base backup.

This will mean some changes to the logic around WAL cleanup - specifically making sure that we preserve the WALs required for the consistency of the `keep` backup while deleting everything else up to the oldest backup. This is complex enough that I think it's worth splitting this work into two PRs. One, a refined version of the above branch (with tests) which adds the basic `keep` functionality, and a second which makes it possible to specify `--target standalone` or `--target full` and changes the WAL cleanup logic accordingly.
