### ISSUE TITLE
Barman Cloud: Add support for Azure Storage Account SAS Token at Blob Container level

### ISSUE THREAD

**Issue by valeriodelsarto** [EnterpriseDB/barman#388]
The current version of Barman Cloud doesn't support the [SAS Tokens generated at the Blob Container level](https://docs.microsoft.com/en-us/cli/azure/storage/container?view=azure-cli-latest#az_storage_container_generate_sas), it only supports [SAS Tokens generated at the Storage Account level](https://docs.microsoft.com/en-us/cli/azure/storage/account?view=azure-cli-latest#az_storage_account_generate_sas). This feature will allow a more granular set of credentials accessing the object storage.

**Comment by mikewallace1979** [comment]
I thought the issue was that we were creating a `BlobServiceClient` and using that to create the `ContainerClient` however on further testing it turns out it was the use of `ContainerClient.exists` which required more permissions than a blob-container SAS token had (it needs to be able to [list all containers under the storage account,](https://stackoverflow.com/a/65102866) which isn't possible with a blob-container-level token).

So the PR contains both an alternative to calling `ContainerClient.exists` and changes in initialising the client so that we create `ContainerClient` directly. Although the second change isn't necessary to fix the issue I think it's worth keeping anyway as it simplifies the code (and the tests).
