### ISSUE TITLE
Implement new barman and/or barman-cloud subcommands to test the archive-destination contents

### ISSUE THREAD

**Issue by mnencia** [EnterpriseDB/barman#432]
We could add an option to `barman-cloud-wal-archive` to enable the following behavior:

1. when archiving the very first WAL file (000000010000000000000000), `barman-cloud-wal-archive` should fail if the target position contains any backup or WAL
2. when archiving the first file of a WAL segment (XXXXXXXXXXXXXXX0000000), `barman-cloud-wal-archive` should fail if the target contains any WAL in that segment

the rationale is to prevent mixing WALs from different instances.

**Comment by gbartolini** [comment]
I agree this is an important feature that would allow us to catch in an easier way sharing the same bucket with different servers. Maybe an option "--require-empty-target"?

**Comment by mikewallace1979** [comment]
@ringerc

The proposed PR #441 adds `barman-cloud-check-wal-archive <SERVER_URL>` and `barman check-wal-archive` commands.

These accept `--current-wal-segment` and `--current-timeline` arguments. If neither are set the command will exit with status 1 if there are any WALs in the archive at all. If both are set then the command will check all the WALs and exit with status 1 unless the archive is empty or only consists of files which can be ignored (i.e. they are history files which are < current_timeline, they are WAL segments < the current timeline, or they are WAL segments on the current timeline but < the current WAL segment).

If either `--current-wal-segment` *or* `--current-timeline` are set (but not the other) then an error is generated and we exit with status 2 (as we would for other error conditions).

I didn't add the `--for-new-cluster` and `--for-promotion` flags because they're not essential for the functionality (the presence of `--current-wal-segment` and `--current-timeline` is enough to change the behaviour of the check) and the names refer to concepts which barman doesn't know anything about - I'm not convinced it makes sense to tell barman-cloud why it needs to do a check, we should only be giving it the details of what should be included in the check.

If those flags would still be helpful to external automation scripts then let me know and we can still add them.

One other thing to clarify - the PR currently assumes `--current-wal-segment` is the logical ID and the segment ID combined, e.g. `0000000100000001` - is that what you're expecting?

**Comment by ringerc** [comment]
@mikewallace1979 Thanks. Just saw this (GH not notifying me for some reason). Will look.
