### ISSUE TITLE
Backups waiting to finalize on Standbys 

### ISSUE THREAD

**Issue by lucianobotti** [EnterpriseDB/barman#448]
In an specific configuration, when taking `rsync - concurrent` backups on a Standby with `archive_mode = always`, the barman backups taken on this server (specially when the load is low on the primary server) will wait with a message like: 
`Asking PostgreSQL server to finalize the backup.`

Backups would normally end when the primary server switches to a new wal file or in case it is forced with `pg_swithch_wal()`. 

From the documentation PG >= 10:

https://www.postgresql.org/docs/14/functions-admin.html#:~:text=There%20is%20an%20optional%20second%20parameter%20of%20type%20boolean.%20If%20false%2C%20the%20function%20will%20return%20immediately%20after%20the%20backup%20is%20completed%2C%20without%20waiting%20for%20WAL%20to%20be%20archived.%20This%20behavior%20is%20only%20useful%20with%20backup%20software%20that%20independently%20monitors%20WAL%20archiving

For this case, seems the code on `pg_stop_backup` could make a better use of the second option `wait_for_archive=false` in order to finalize the backup command. It can also make a better use of the settings `--wait` and `--wait-timeout`, as we believe that was the intention.

Mentioning @martinmarques and @tureba as they have been involved in some testings.

**Comment by tureba** [comment]
In effect, it would mean changing line https://github.com/EnterpriseDB/barman/blob/master/barman/postgres.py#L1242

From: `pg_stop_backup(FALSE)`

To never wait for archiving: `pg_stop_backup(FALSE, FALSE)`

Or to give it a boolean in the second argument indicating if the user provided the `--wait` argument or not.

I think the first option is adequate for Barman.

**Comment by martinmarques** [comment]
FYI, this is related to a customer ticket RT75337

**Comment by mikewallace1979** [comment]
To summarize, the change here is going to be:
* Barman will use `wait_for_archive=FALSE` when calling `pg_stop_backup`.
* This means the backup will finish whether or not PostgreSQL considers the required WALs to have been archived - this will resolve the issue where backups cannot complete on standby servers unless a WAL switch happens to occur on the primary.

The following behaviour will be unchanged:
* Backups for which Barman does not yet have the required WALs will continue to be in status `WAITING_FOR_WALS` until a subsequent `barman cron` run finds that the required WALs have been archived.
* The `--wait` flag will cause `barman backup` to wait until barman determines the required WALs have been archived before returning.
* The `--wait-timeout` flag determines how long `barman backup` will wait.

This only applies to PostgreSQL >= 10. Earlier versions will continue to wait at the `pg_stop_backup` stage since there is no `wait_for_archive` option.

**Comment by mikewallace1979** [comment]
After a lot of testing and discussion the workaround proposed in PR #580 is being abandoned in favour of #596.

**Comment by mikewallace1979** [comment]
The underlying issue here should be resolved by #596.
