### ISSUE TITLE
Barman Backup Issues

### ISSUE THREAD

**Issue by wasiualhasib** [EnterpriseDB/barman#492]
Not able to backup after recover. I am trying to backup but it continuously working not ending its activity. It keep working and working. Where is my issue? Need expert opinion. All necessary details I have given below images. 

![image](https://user-images.githubusercontent.com/48445960/149676650-8a846ec4-5551-4e66-ba72-a8ba7abfb750.png)
![image](https://user-images.githubusercontent.com/48445960/149676679-ee52cebb-538d-4d4a-a7d0-f8295f6a5dcb.png)

![image](https://user-images.githubusercontent.com/48445960/149676622-eff0443d-561a-4294-b784-b384ac9d8fbb.png)

![image](https://user-images.githubusercontent.com/48445960/149676559-24466f5b-e006-43d8-a1ee-3b753a0ef9cf.png)

**Comment by mikewallace1979** [comment]
Hi @wasiualhasib - based on the barman logs it looks like the `pg_basebackup` command invoked by barman is hanging. Unfortunately barman does not currently log the output of `pg_basebackup` while it is running so to find out what's going wrong you will need to find the exact `pg_basebackup` command barman runs and execute it manually.

For example, while the barman backup command is running:

    $ ps -eaf | grep pg_basebackup
    barman    4958  4955  0 10:40 pts/0    00:00:00 /usr/lib/postgresql/12/bin/pg_basebackup --dbname=dbname=replication host=recovery options=-cdatestyle=iso port=5432 replication=true user=postgres application_name=barman_streaming_backup -v --no-password --pgdata=/var/lib/barman/main/base/20220117T104049/data --no-slot --wal-method=none --checkpoint=fast

    $ pg_basebackup --dbname='dbname=replication host=recovery options=-cdatestyle=iso port=5432 replication=true user=postgres application_name=barman_streaming_backup' -v --no-password --pgdata=/tmp/test_backup --no-slot --wal-method=none --checkpoint=fast
    pg_basebackup: initiating base backup, waiting for checkpoint to complete
    ...

Note the following:
* The values of the `pg_basebackup` arguments will differ on your system.
* You will need to add quotes around the --dbname argument.
* You should point `--pgdata` to an empty destination directory.

Let the command run for a while and share the output here (along with the full `pg_basebackup` command) - hopefully this will provide some clues as to what the problem is.

**Comment by wasiualhasib** [comment]
**To recover my database I did following steps whether below steps are right for recover:**
1. I did repmgr service pause all node.
2. postgresql instance stop.
3. next recover using barman on primary node.
4. Next start postgresql instance on parimary node
5. repmgr service unpause

I did clone again from primary, is it right way for recover because it takes long time  . What need to be done for standby without cloning?

**Comment by wasiualhasib** [comment]
Issue was that after recover from barman backup it makes archive_command=false. Because of that I found it ganging up backup process.

**Comment by mikewallace1979** [comment]
That's right - barman does this to avoid the possibility of having multiple postgres servers (the original and the recovered, for example) archiving to the same location. Archiving can be re-enabled once you have either verified the original server is gone for good, or archive_command can be updated to use a new location.

I filed #493 to improve the reporting of `pg_basebackup` progress.
