### ISSUE TITLE
Failed backup at the finalize step reports it was issuing a "start" command

### ISSUE THREAD

**Issue by tureba** [EnterpriseDB/barman#496]
When a backup fails at the end, one message shows up in the logs saying it failed issuing the "start backup command". That is a bit misleading, since it was probably trying to run a `pg_stop_backup()` at the moment.

This is an example of log:

```
2022-01-19 03:44:00,965 [1776434] barman.backup_executor INFO: Asking PostgreSQL server to finalize the backup.
2022-01-19 03:44:00,966 [1776434] barman.backup ERROR: Backup failed issuing start backup command.
DETAILS: Connection lost, reconnection not allowed
```

In the above, the misleading message is the second line (the other ones were provided only for context).

I believe the message in the second line should say "Backup failed issuing stop backup command" instead or a similar adjustment.

**Comment by didiermichel** [comment]
Hi @tureba , 
Thank you for the report.  There is something inconsistent about this indeed. 
Can you give a bit more context (local or remote backup) and if you have more logs before the issue. (even better running backup command with `--log-level DEBUG`)

**Comment by tureba** [comment]
It's tough to ask the customer to run it with debugging enabled, since the message comes up with failed backups and we fixed theirs around the time I reported this issue.
I'll try to bake an artificial test case in the next few days, though. I believe all it should take is for the backup to start correctly, then fail at the last step, which I might be able to accomplish by interrupting the network access in the right moment.

**Comment by mikewallace1979** [comment]
I did a few experiments injecting failures into the backup and the problem is that the current_action of the backup strategy is not updated from "issuing start backup command" immediately before the stop backup process starts.

* At the beginning of the backup, the [start_backup function of the backup strategy is called](https://github.com/EnterpriseDB/barman/blob/6b8ac52ce696c8395e7338371bba5db8cf0d74b2/barman/backup_executor.py#L773). This sets the [current_action](https://github.com/EnterpriseDB/barman/blob/6b8ac52ce696c8395e7338371bba5db8cf0d74b2/barman/backup_executor.py#L1353) of the strategy to "issuing start backup command".
* The current_action of the backup executor changes to ["copying files"](https://github.com/EnterpriseDB/barman/blob/6b8ac52ce696c8395e7338371bba5db8cf0d74b2/barman/backup_executor.py#L797) and then, if no exceptions are raised, to ["issuing stop of the backup"](https://github.com/EnterpriseDB/barman/blob/6b8ac52ce696c8395e7338371bba5db8cf0d74b2/barman/backup_executor.py#L812).
* In the finally block, the [stop_backup function of the backup strategy is called](https://github.com/EnterpriseDB/barman/blob/6b8ac52ce696c8395e7338371bba5db8cf0d74b2/barman/backup_executor.py#L816) and this sets the [current_action](https://github.com/EnterpriseDB/barman/blob/6b8ac52ce696c8395e7338371bba5db8cf0d74b2/barman/backup_executor.py#L1753) of the strategy to "issuing stop backup command".

The reason the current_action of the strategy gets logged is because the `current_action` of the executor is updated to match the `current_action` of the strategy in the exception handling [inside the finally block](https://github.com/EnterpriseDB/barman/blob/6b8ac52ce696c8395e7338371bba5db8cf0d74b2/barman/backup_executor.py#L815-L819). While the stop_backup function of the strategy does change the `current_action` from "issuing start backup command" to ["issuing stop backup command"](https://github.com/EnterpriseDB/barman/blob/6b8ac52ce696c8395e7338371bba5db8cf0d74b2/barman/backup_executor.py#L1753) there is a line of code before this change which calls `self.postgres.server_version` - if [this call](https://github.com/EnterpriseDB/barman/blob/6b8ac52ce696c8395e7338371bba5db8cf0d74b2/barman/backup_executor.py#L1752) fails then, even though we are attempting to stop the backup, the current_action of the strategy will still be "issuing start backup command" and therefore that is what will get logged.

Given calling `self.postgres.server_version` involves the psycopg2 connection and a potential network call there is plenty of opportunity for this to fail resulting in the misleading error message.

We should therefore swap [these lines](https://github.com/EnterpriseDB/barman/blob/6b8ac52ce696c8395e7338371bba5db8cf0d74b2/barman/backup_executor.py#L1752-L1753) so that current_action is updated before we attempt to fetch the postgres version - this removes the loophole which allows Barman to report the failure to stop the backup under the "issuing start backup command" action.
