### ISSUE TITLE
Standby not attached with primary, it says timeline 6 forked off current database.

### ISSUE THREAD

**Issue by wasiualhasib** [EnterpriseDB/barman#500]
1. Recovery from Barman to primary node.
2. Clone from primary to standby using barman
3.  Starting postgresql13
4. unable to standby follow
5.  unable to node  rejoin. 

Don't understand why it said "rejoin target server's timeline 6 forked off current database system timeline 5 before current recovery point 0/7A000000". To overcome this issue what need to do?

![image](https://user-images.githubusercontent.com/48445960/150671884-68a9e885-6808-4d17-8b92-01f99457b6d6.png)
![image](https://user-images.githubusercontent.com/48445960/150672276-629c57bb-2a58-490a-999f-b10f4d1babb4.png)
![image](https://user-images.githubusercontent.com/48445960/150672363-c56fa51e-1f00-4938-991c-78f681f7401a.png)

**Comment by mikewallace1979** [comment]
@wasiualhasib The message "rejoin target server's timeline 6 forked off current database system timeline 5 before current recovery point 0/7A000000" is telling you that the primary server moved to timeline 6 before the current position of the standby on timeline 5, which means the two servers do not share the same history.

Without knowing the full context it's not possible to say how this happened though one possibility is that the primary was not recovered from the most recent backup. When the standby was then cloned from barman it would have been cloned from the most recent backup which would be further ahead on timeline 5. This is just a guess though - if it turns out this was the case then you could try taking another backup of the primary and cloning your standby from that.

There are a lot of moving parts here and it is not clear that there is a specific issue with barman. You may find you can get more specific advice about repmgr and timelines on the repmgr mailing list: https://groups.google.com/group/repmgr
