### ISSUE TITLE
WALRECEIVE not running after reboot

### ISSUE THREAD

**Issue by emamuse86** [EnterpriseDB/barman#554]
Hello ,

today we have found a problem relative the process pg_walreceive. After a system reboot, the barman check result was all OK for every check.

But if we check with "ps -ef | grep receive" we haven't any process active.

We have tried to execute:

barman receive-wal <db> --stop
barman receive-wal <db> --reset

without success.

The only solution we have found was to delete all receive-wal.lock files in barman home.

There are some patches about this problem?

Thank you

**Comment by mikewallace1979** [comment]
@emamuse86 thanks for reporting this issue - can you share the version of Barman you are using?

The only scenario I can of which would result in what you describe is that if a flock already exists on the `<server-name>-receive-wal.lock` file. If this scenario occurred then:

1. `barman check` would return `pg_receivexlog: OK` because if it is unable to acquire a lock then it assumes that the pg_receivewal process is running.
2. `barman receive-wal` would fail because it would be unable to acquire the lock.
3. `barman receive-wal --stop` would return successfully but not stop the process or cause the lock to be removed (since there is no process actually running).
4. `barman receive-wal --reset` would fail because it would not be able to acquire the lock.

I don't know exactly how this situation would come about however it seems as though Barman could do a better job of detecting it (`barman check` should not simply assume being unable to acquire a lock means the process is running, for example) and perhaps provide tools to resolve things such as cleaning up lock files.

**Comment by martinmarques** [comment]
I believe this was solved when we added the orphaned locks cleanup in 3.10
