### ISSUE TITLE
PITR date validation on recovery

### ISSUE THREAD

**Issue by didiermichel** [EnterpriseDB/barman#556]
When doing PITR recovery, Barman recovery with `barman recover --target-time 'YYY-mm-dd HH:MM:SS'` options could lead to PostgresSQL restoration failure if the requested date is not in the available restoration time bracket.  

Indeed, Barman behavior is to transmit PITR settings through to PostgreSQL. There is no validation on barman side.
When PostgreSQL tries to reach the expected time in restoration, it will fail is this is an impossible time request.

This brings a low user experience and we should search a more acceptable behavior to improve this.

A possible solution suggested by @mikewallace1979  could be to  use `get-wal` command to extract wals (and extract them if compressed)  in  a temporary directory and then use `pg_waldump` to have access to available times for validation.

This first mitigation approach is still to be discussed and prioritized

**Comment by mikewallace1979** [comment]
One thing worth noting is that this check in Barman is not strictly necessary for PostgreSQL versions below 13 because PostgreSQL <13 would just promote the server without further notice if the archive ended before the recovery target was reached. This behaviour was changed in PostgreSQL 13 so that reaching the end of the archive before the recovery target now raises a fatal error (see the [relevant PG commit](https://github.com/postgres/postgres/commit/dc788668bb269b10a108e87d14fefd1b9301b793)).

Since Barman manages the WAL archive it has all the information it needs to determine whether the requested timestamp is before or at the most recent transaction in the archive on the requested timeline therefore Barman could do several helpful things here:

1. Raise an error if a target time is requested which is greater than the most recent transaction time in the WAL archive on the requested timeline.
2. Tell the user the timestamp of the most recent transaction in the WAL archive on a given timeline.

If a user just wants to restore to the most recent point on a given timeline then the existing `--target-tli` option would do this form them so just the above two points would be sufficient to improve the user experience.

**Comment by martinmarques** [comment]
In order to get the timestamp of the transactions we'd need to do invasive checks on the WALs (using `pg_waldump`). We've discussed this with  @gcalacoci and @barthisrael and we feel that this would put a lot of load on the barman server, with very little returned value.
Like two options could happen:
- The timestamp is before the consistent state. This we can verify by checking the end_backup in the backup.info
- The timestamp is at a time in the future of the last WAL archived. In this case, or the user made a mistake, or maybe archiving was lagging and the WAL hadn't been written yet to the barman server. In the second case, `--get-wal` would fix it.

One option would be to write a small C app which does something similar to `pg_waldump` but only reads the first and last transaction in the WAL and keeps the information in xlog.db.

**Comment by barthisrael** [comment]
> * The timestamp is before the consistent state. This we can verify by checking the end_backup in the backup.info

FWIW this check is simple and it is already performed by the code -- see https://github.com/EnterpriseDB/barman/blob/release/3.10.1/barman/recovery_executor.py#L495-L502
