### ISSUE TITLE
Is it safe to call barman-cloud-wal-archive on multiple threads to upload files faster?

### ISSUE THREAD

**Issue by vivekpradhan** [EnterpriseDB/barman#557]
My postgres pg_wal directory is getting filled up due to the command running a bit slow (16MB files takes about 8 seconds on avg). As a workaround I thought I can use archive_command to move the file to a different location. Then upload the files with multiple threads to google cloud.

I am worried that since this will not guarantee the order in which the files are uploaded it might drop some files since they are older than what's already in the cloud.

Also if you know a better solution please let me know. (We are trying to cut some cost by not having a separate VM for barman)

**Comment by didiermichel** [comment]
Hello @vivekpradhan. Thank you for opening this issue.

What I understand is that you want to use `barman-cloud-wal-archive` to save new wals into a GCS bucket. 
And you want to perform parallel `barman-could-wal-archive` commands for older wals. Am I correct?

Note that you should know that if your PG server is outside GCP network, you may experience slow network transfer. So that is something you want to test first. So at the moment, the best configuration to use barman cloud on GCP is to have PG server running on a GCP VM or something similar.

**Comment by vivekpradhan** [comment]
So I have been using `barman-cloud-wal-archive` as archive_command for PG server inside GCP, to backup to GCS bucket. It works fine, but when I added a new dataset that resulted in high volume of wal files it could not keep up. Now my wal files folder is huge (backlog of 40000 16MB files). As a solution I thought I can change archive_command to `cp %f different_location` Then run `barman-cloud-wal-archive different_location/filename` in parallel, something like this:

```
p = process_pool(jobs=10)
for file in "different_location":
    barman-cloud-wal-archive file
```
I just wanted to know if this is okay to do.

**Comment by mikewallace1979** [comment]
Yes it would be safe to run multiple `barman-cloud-wal-archive` commands in separate processes to archive multiple WAL files in parallel to GCS.

At the risk of stating the obvious, it would be important to check the exit status of these processes since PostgreSQL is no longer going to be aware of any errors beyond the initial `cp %f different_location`. You will also need to remove the WALs from `different_location` once `barman-cloud-wal-archive` has completed successfully.

An alternative option would be to try [pgBackRest](https://pgbackrest.org/) which has built-in support for asynchronous parallel WAL archiving.

**Comment by vivekpradhan** [comment]
Thanks for the response. I will check which solution works best for me.
