### ISSUE TITLE
--no-verify-ssl parameters for s3 cloud-provider

### ISSUE THREAD

**Issue by WillyRL** [EnterpriseDB/barman#639]
Hi Barman Community, 

I can't find any documentation about ignoring the SSL Verification, as we know, in aws-cli we can ignore the SSL verification using
 `--no-verify-ssl`  param. 

I need to ignore the SSL Verification because I'm using self-signed minio s3 compatible storage for the remote backup.

Thank You

**Comment by mikewallace1979** [comment]
Barman doesn't provide an equivalent to `--no-verify-ssl` however boto3 will use either [AWS_CA_BUNDLE](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#using-environment-variables) or the `ca_bundle` variable if it is set in the configuration profile, so you could point that to your self-signed root CA which should allow boto3 to verify the SSL certificate used by your minio instance.

**Comment by WillyRL** [comment]
How if the SSL Certificate generated without any CA ?

**Comment by mikewallace1979** [comment]
Your best option would be to create your own CA and use that to sign the server certificate for your minio instance instead of generating a self-signed server certificate directly (it's only a couple of additional openssl commands). This would allow everything to work without having to disable SSL host verification.

If you still want to disable verification then the relevant line in the Barman python code is [here](https://github.com/EnterpriseDB/barman/blob/5beca2c3c5f7c6ddb6efe384a523ea7c06fac1e6/barman/cloud_providers/aws_s3.py#L135) - you could patch that file on your local system and add the `verify=False` option.

**Comment by WillyRL** [comment]
I have figured it out by myself yesterday, anyway Thank you @mikewallace1979 !
