### ISSUE TITLE
Output of barman sync-info run by cron is written to logfile when log_level set to INFO

### ISSUE THREAD

**Issue by hzetters** [EnterpriseDB/barman#682]
Hi,
After upgrading our test-installation of barman (one active and one passive node) from Barman 2.19 to version 3.2.0 I noticed that the output of the barman sync-info command, that is run by barman cron on the passive node, is written to the barman logfile when you 
have log_level set to INFO.
This was not the case in version 2.19 and it is flooding the logfile.
Need log_level INFO to log when the actual sync of the backups from the active server are being performed but it is really inconvenient to have the output of the barman sync-info command for each configured server written to the logfile every time barman cron runs (every minute).

As this was not the case in version 2.19 I hope it can be excluded again.

Thanks!

**Comment by mikewallace1979** [comment]
Thank you for the bug report @hzetters - it looks like this was a side-effect of [a more general change introduced in 3.1.0](https://github.com/EnterpriseDB/barman/commit/8808725e569c4b0ccf435134a801b94f704ef031) which allowed the output of `pg_basebackup` to be written to the logs at INFO level while the backup was in progress. Unfortunately the change didn't consider whether logging stdout at INFO level would be appropriate for all other Unix commands executed by Barman.

We could fix this by making the in-progress logging of stdout INFO level only for `pg_basebackup` commands. For all other commands we can either log at DEBUG level or disable in-progress logging altogether since the command output is already logged on command completion at DEBUG level.
