### ISSUE TITLE
Barman backup failed(Streaming)

### ISSUE THREAD

**Issue by mrudula09attili** [EnterpriseDB/barman#716]
Hello Team,

  My barman backup failed with the below error message.
 This is initial setup of the barman streaming on a new VM (barman) and new postgresql v14 VM.

barman.backup ERROR: Backup failed copying files.
DETAILS: data transfer failure on directory '<barman_backup_location>/pg_VM/base/20221214T104619/data'
pg_basebackup error:
pg_basebackup: initiating base backup, waiting for checkpoint to complete
pg_basebackup: checkpoint completed
pg_basebackup: error: could not get COPY data stream: ERROR:  could not open file "./deletethis/server.key": Permission denied
pg_basebackup: removing contents of data directory "<barman_backup_location>/pg_VM/base/20221214T104619/data"
pg_basebackup: changes to tablespace directories will not be undone
2022-12-14 13:41:43,954 [1047945] barman.hooks WARNING: /var/lib/barman/post_hook.sh returned 126
Output details:
/bin/sh: /var/lib/barman/post_hook.sh: Permission denied

The below has been changed now, I have giving 0755 for this file.
"/bin/sh: /var/lib/barman/post_hook.sh: Permission denied"

Thanks,
Sri Attili

**Comment by mikewallace1979** [comment]
Check the ownership and permissions of the file `./deletethis/server.key` in the PGDATA directory on your PostgreSQL hosts. It looks like PostgreSQL isn't able to read it during the backup and this is causing the backup to fail.

**Comment by mikewallace1979** [comment]
@mrudula09attili I don't see anything concerning in the `barman diagnose` output other than the error also reported in the `barman backup` output.

Did you check the ownership and permissions of the file `./deletethis/server.key`? The presence of the following error message suggests that PostgreSQL is trying to read that file during the backup and failing due to a permissions error:

    pg_basebackup: error: could not get COPY data stream: ERROR: could not open file "./deletethis/server.key": Permission denied

If that file, or any other files in PGDATA on the PostgreSQL server, cannot be read by the user running PostgreSQL then pg_basebackup is going to fail.

**Comment by martinmarques** [comment]
Closing due to lack of feedback
