### ISSUE TITLE
Question: understanding Flush LSN of barman replication-status

### ISSUE THREAD

**Issue by feliperaul** [EnterpriseDB/barman#787]
Using barman with streaming replication, I get this status:

```
barman replication-status pg

Status of streaming clients for server 'pg':
  Current LSN on master: 64/BFE544D8
  Number of streaming clients: 1

  1. Async WAL streamer
     Application name: barman_receive_wal
     Sync stage      : 3/3 Remote write
     Communication   : TCP/IP
     IP Address      : xx / Port: xx / Host: -
     User name       : streaming_barman
     Current state   : streaming (async)
     Replication slot: barman
     WAL sender PID  : 1422084
     Started at      : 2023-04-15 23:59:15.224720+00:00
     Sent LSN   : 64/BFE544D8 (diff: 0 B)
     Write LSN  : 64/BFE544D8 (diff: 0 B)
     Flush LSN  : 64/BF000000 (diff: -14.3 MiB)
```

According to ChatGPT, my Flush LSN "_has a difference of -14.3 MiB, **which is a significant difference**. It means that the backup server has not yet flushed 13.5 MiB of WAL data to disk and"it seems that your backup is not fully in sync_."

I couldn't find any information regarding this Flush LSN status. Is this number normal, expected to grow until the next full backup, or there's something actually wrong with my barman? 

Every single restoration test we did there was no data loss, and `barman check pg` returns all green, as does `barman status pg`.

**Comment by mikewallace1979** [comment]
Hi @feliperaul - this looks to me like everything is behaving as intended and nothing is wrong with your `barman`.

Flush LSN is the value of `flush_lsn` in the [`pg_stat_replication` view](https://www.postgresql.org/docs/current/monitoring-stats.html#MONITORING-PG-STAT-REPLICATION-VIEW) for the streaming replication process which sends the WAL updates to the Barman server.

This is telling you that the `pg_receivewal` process which Barman uses as the streaming client has written up to LSN `64/BFE544D8` but last flushed to disk at LSN `64/BF000000` - this is [by design](https://www.postgresql.org/docs/current/app-pgreceivewal.html):

> Unlike the WAL receiver of a PostgreSQL standby server, pg_receivewal by default flushes WAL data only when a WAL file is closed.

So under normal operation, `pg_receivewal` will write the WAL data to a file in Barman's `<SERVER_NAME>/streaming` directory and manually flush the data to disk when finalising the WAL segment. At this point, Barman's archiving process (triggered by `barman cron`) will copy the complete WAL segment into Barman's WAL archive so that it can be used during recovery.

Should the `pg_receivewal` process terminate and there happens to be data which is written but not flushed then the data will be streamed from PostgreSQL when the `pg_receivewal` process restarts.

**Comment by feliperaul** [comment]
@mikewallace1979 Thank you!
