### ISSUE TITLE
Barman backup error

### ISSUE THREAD

**Issue by angorrilla** [EnterpriseDB/barman#802]
Hi,
Using barman 3.0.1 to backup several servers, but one of them, after a lot of time working fine, now complains with:
ERROR: failure issuing stop backup command (Connection lost, reconnection not allowed)

I have tried executing pg_stop_backup() on target database but I get:
ERROR:  exclusive backup not in progress

Also I checked ssh_command from barman.conf for that server (ssh postgres@targetserver -q) and its works properly without asking for password.

In barman server "incoming" folder is updated continuously and a "show-server" executed over failing server always show an updated "last_archived_wal".

In database server I have checked that already exists an rsync process uploading pg_wal folder. 

Please, could somebody help with that issue?

Thanks.

**Comment by mikewallace1979** [comment]
Hi @angorrilla - this issue happens when the PostgreSQL connection used to start and stop the backup is terminated during the backup. Unfortunately the first time Barman becomes aware the connection has disconnected is at the end of the backup when it attempts to call `pg_stop_backup` (or `pg_backup_stop` with PostgreSQL >= 15).

For concurrent backups, which are the default with Barman >= 3.0.0, PostgreSQL requires that `pg_backup_stop` is called on the same PostgreSQL connection which was used to call `pg_backup_start`, so once that PostgreSQL connection has been lost there is no way of successfully completing the backup.

There are a few things you can try:

1. Upgrade to Barman 3.5.0. This contains a [bug fix](https://github.com/EnterpriseDB/barman/blob/c029e4d263b08b54884522904c30159b45ca6ffa/NEWS#L53-L54) which [disables `idle_session_timeout`](https://github.com/EnterpriseDB/barman/commit/975924c38af014366a4709a7b843da0904b1ac9f) in the PostgreSQL session used to start/stop the backup.
2.  Try lowering the value of `tcp_keepalives_idle` in PostgreSQL as suggested in [#665](https://github.com/EnterpriseDB/barman/issues/665#issuecomment-1408509414).
3. If you are using a PostgreSQL earlier than 15, you can switch to exclusive backups by setting `backup_options = exclusive_backup` in the Barman configuration. This is not recommended as exclusive backups have been deprecated for a long time (and removed in PostgreSQL 15) however it may help as a short term workaround.

**Comment by angorrilla** [comment]
Hi @mikewallace1979,
Thanks a lot for your help!
I chose third option to do not affect other PostgreSQL server with changes and it worked perfectly.

 Thanks.
