### ISSUE TITLE
Barman fails during backup with "can't extract backup id"

### ISSUE THREAD

**Issue by btxbtx** [EnterpriseDB/barman#835]
I am running barman within the context of cloudnative-pg (pg-operator chart version `0.18.0`).   I've not changed anything about the default barman config they use.  I noticed that my backups are performing, at least partially, before eventually failing with `can't extract backup id`.

The logs:

```js
my-cluster-2 postgres {
  "level": "info",
  "ts": "2023-07-26T09:12:07Z",
  "msg": "WAL archiving is working",
  "logging_pod": "my-cluster-2"
}
my-cluster-2 postgres {
  "level": "info",
  "ts": "2023-07-26T09:12:07Z",
  "msg": "Backup started",
  "backupName": "cnpg-backup",
  "backupNamespace": "cnpg-backup",
  "logging_pod": "my-cluster-2",
  "options": [
    "--user",
    "postgres",
    "--name",
    "backup-1690362727",
    "--endpoint-url",
    "<my s3 compatible storage>",
    "--cloud-provider",
    "aws-s3",
    "<my s3 destination>",
    "my-cluster"
  ]
}
my-cluster-2 postgres {
  "level": "info",
  "ts": "2023-07-26T09:12:29Z",
  "msg": "Backup completed",
  "backupName": "cnpg-backup",
  "backupNamespace": "cnpg-backup",
  "logging_pod": "my-cluster-2"
}
my-cluster-2 postgres {
  "level": "error",
  "ts": "2023-07-26T09:12:30Z",
  "logger": "barman",
  "msg": "Can't extract backup id",
  "logging_pod": "my-cluster-2",
  "command": "barman-cloud-backup-show",
  "options": [
    "--format",
    "json",
    "--endpoint-url",
    "<my s3 compatible storage>",
    "--cloud-provider",
    "aws-s3",
    "<my s3 destination>",
    "my-cluster",
    "backup-1690362727"
  ],
  "stdout": "",
  "stderr": "2023-07-26 09:12:30,354 [273] ERROR: Barman cloud backup show exception: Unknown backup 'backup-1690362727' for server 'my-cluster'\n",
  "error": "exit status 4",
  "stacktrace": "github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/barman.executeQueryCommand\n\tpkg/management/barman/backuplist.go:87\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/barman.GetBackupByName\n\tpkg/management/barman/backuplist.go:140\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).getExecutedBackupInfo\n\tpkg/management/postgres/backup.go:383\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).takeBackup\n\tpkg/management/postgres/backup.go:352\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).run\n\tpkg/management/postgres/backup.go:267"
}
my-cluster-2 postgres {
  "level": "error",
  "ts": "2023-07-26T09:12:30Z",
  "msg": "Backup failed",
  "backupName": "cnpg-backup",
  "backupNamespace": "cnpg-backup",
  "logging_pod": "my-cluster-2",
  "error": "exit status 4",
  "stacktrace": "github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).run\n\tpkg/management/postgres/backup.go:271"
}
```

Happy to provide more config if it is helpful, just let me know what is needed.

**Comment by mikewallace1979** [comment]
Hi @btxbtx - I've created a local cnpg cluster using the 0.18.0 chart to reproduce this issue but so far my backups to a local minio container are working as expected.

Are you able to get a shell on one of the PostgreSQL pods via `kubectl exec`? If so, could you please run the following commands and post the output here?

```
AWS_ACCESS_KEY_ID=<access key id> AWS_SECRET_ACCESS_KEY=<secret access key> barman-cloud-backup-list <my s3 destination> my-cluster --endpoint-url=<my s3 compatible storage>
AWS_ACCESS_KEY_ID=<access key id> AWS_SECRET_ACCESS_KEY=<secret access key> barman-cloud-backup-show <my s3 destination> my-cluster backup-1690362727 --endpoint-url=<my s3 compatible storage>
```

If either of the above commands fail please retry them with the `-vv` option and post the output.

If you can't get a shell on the pods, could you list the backup IDs saved in your object store? They should be available under `my-cluster/base` prefix.

Also, which s3-compatible object store are you using?

Thanks.

**Comment by mikewallace1979** [comment]
Thanks for providing the additional information. The fact that the operator logs `Backup completed` while the `barman-cloud-backup-list` command shows no backups is particularly concerning.

I tried reproducing this issue using linode object storage this morning but have still not had any success.

Can you try taking a manual backup in a shell on one of the pods? You will need to export `TMPDIR` so that a writable filesystem is used for temporary files - something like this should work:

    TMPDIR=/controller AWS_ACCESS_KEY_ID=<access key id> AWS_SECRET_ACCESS_KEY=<secret access key> barman-cloud-backup --user=postgres --name=backup-test s3://barmantest --endpoint-url=https://<my-endpoint>.linodeobjects.com --cloud-provider=aws-s3 cnpg-cluster -vv
    
Redacting the same things as last time should be fine.

It would definitely be helpful at this point to see a list of the objects present in the linode object store after the backup has completed - can you include that in some form, preferably with the full object keys? Even if the backups aren't being written there should still be archived WALs present and it would be good to just verify that things are ending up where they should be.

**Comment by mikewallace1979** [comment]
@btxbtx thanks - this was exactly the information I wanted because I hoped to verify:

1. the underlying backup process is completing successfully
2. the underlying backup process is actually writing objects into the object store

Both of these things are true which is good but unfortunately means we're no closer to understanding why the `barman-cloud-backup-show` command fails.

The fact that both `barman-cloud-backup-list` and `aws s3 ls` both act as if running against an empty bucket feels significant but I can't think of any obvious reasons why this would happen - I'll read through the logs in more detail give it some more thought.

**Comment by mikewallace1979** [comment]
Thanks for ruling out permissions - I forgot to say in my last response but yes, the cnpg manifest files would also be useful.

**Comment by mikewallace1979** [comment]
I can see something which might be significant:

In the output for `barman-cloud-backup` we can see a POST request being made to `/barmantest/cnpg-cluster/base/20230824T033954/data.tar` - this matches the location of the backups listed by the linode UI `barmantest/cnpg-cluster/base`.

However, in the output for both `barman-cloud-backup-list` and `barman-cloud-backup-show` there are GET requests to `/barmantest` which are providing a path of `cnpg-cluster-1`, e.g.:

```
GET
/barmantest
delimiter=%2F&encoding-type=url&list-type=2&prefix=cnpg-cluster-1%2Fbase%2F
```

cnpt-cluster-1 is the pod name rather than the cluster name so if the operator is also running those commands with the pod name instead of the cluster name then that would explain why it can't find the backups, however I also realise this ouput is from manual commands rather than those run by the operator so we can't make that conclusion just yet.

Can you check the options for the `Can't extract backup id` log line for a recent failed backup and check the cluster name definitely matches the cluster name in the options of the `Backup started` log line for that same backup?

**Comment by mikewallace1979** [comment]
I have just reproduced this 🎉 :

<details>
<summary>Operator logs</summary>

```js
{
  "level": "info",
  "ts": "2023-08-25T09:54:25Z",
  "msg": "WAL archiving is working",
  "logging_pod": "cluster-example-2"
}
{
  "level": "info",
  "ts": "2023-08-25T09:54:25Z",
  "msg": "Backup started",
  "backupName": "backup-17",
  "backupNamespace": "backup-17",
  "logging_pod": "cluster-example-2",
  "options": [
    "--user",
    "postgres",
    "--name",
    "backup-1692957265",
    "--gzip",
    "--endpoint-url",
    "https://barman.us-east-1.linodeobjects.com",
    "--cloud-provider",
    "aws-s3",
    "s3://barman/",
    "cluster-example"
  ]
}
{
  "level": "info",
  "ts": "2023-08-25T09:54:36Z",
  "msg": "Backup completed",
  "backupName": "backup-17",
  "backupNamespace": "backup-17",
  "logging_pod": "cluster-example-2"
}
{
  "level": "error",
  "ts": "2023-08-25T09:54:36Z",
  "logger": "barman",
  "msg": "Can't extract backup id",
  "logging_pod": "cluster-example-2",
  "command": "barman-cloud-backup-show",
  "options": [
    "--format",
    "json",
    "--endpoint-url",
    "https://barman.us-east-1.linodeobjects.com",
    "--cloud-provider",
    "aws-s3",
    "s3://barman/",
    "cluster-example",
    "backup-1692957265"
  ],
  "stdout": "",
  "stderr": "2023-08-25 09:54:36,834 [17349] ERROR: Barman cloud backup show exception: Unknown backup 'backup-1692957265' for server 'cluster-example'\n",
  "error": "exit status 4",
  "stacktrace": "github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/barman.executeQueryCommand\n\tpkg/management/barman/backuplist.go:87\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/barman.GetBackupByName\n\tpkg/management/barman/backuplist.go:140\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).getExecutedBackupInfo\n\tpkg/management/postgres/backup.go:383\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).takeBackup\n\tpkg/management/postgres/backup.go:352\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).run\n\tpkg/management/postgres/backup.go:267"
}
{
  "level": "error",
  "ts": "2023-08-25T09:54:36Z",
  "msg": "Backup failed",
  "backupName": "backup-17",
  "backupNamespace": "backup-17",
  "logging_pod": "cluster-example-2",
  "error": "exit status 4",
  "stacktrace": "github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*BackupCommand).run\n\tpkg/management/postgres/backup.go:271"
}
```
</details>

The issue turned out to be the `endpointURL` value - if I use `https://us-east-1.linodeobjects.com` instead of `https://barman.us-east-1.linodeobjects.com` then everything works as expected.

Hopefully if you make the same change to your `endpointURL` that will resolve the original issue.

I don't quite understand why using the bucket URL as the endpoint URL works, or why it behaves differently between the `barman-cloud-backup` and `barman-cloud-backup-show` commands - presumably there's some undefined behaviour somewhere which means that PUT requests via the multipart API will still end up in the right place but GET and HEAD requests won't. I'll do a bit more digging there.

**Comment by mikewallace1979** [comment]
We can keep debugging in this issue for now since the WAL archiving may be related somehow.

Observations from the latest logs:
- It looks like you have backups scheduled every minute, going by the epoch timestamps in the backup names.
- WAL archiving is working and WALs from `00000001000000000000002A` through to `00000001000000000000002F` have been archived while these backups were ongoing.
- One of the backups failed with `Connection was closed before we received a valid response from endpoint URL`. The ID of that backup was `20230825T111717` which maps, via epoch time, to the second backup started in the logs: `cnpg-backup-1692962236`. The URL contains `partNumber=1` which suggests the backup upload had not completed, even though this log line was at 11:22:56, some five minutes after the start of the backup.

It would be useful to know the current wal segment - can you run the following command on the primary pod:

```
psql -c 'SELECT pg_walfile_name(pg_current_wal_lsn());'
```

It would also be useful to know the most recent WAL segment in the linode object store - can you list the contents of the `barmannewtest` bucket under the `cnpg-cluster/wals` prefix?

**Comment by mikewallace1979** [comment]
I haven't had a chance to look through the latest logs in detail but the following line suggests you're trying to start a new cnpg cluster but you're pointing to a bucket which already contains WALs:

```
}
cnpg-cluster-1 postgres {
  "level": "info",
  "ts": "2023-08-25T15:23:04Z",
  "logger": "barman-cloud-check-wal-archive",
  "msg": "2023-08-25 15:23:04,790 [334] ERROR: WAL archive check failed for server cnpg-cluster: Expected empty archive",
  "pipe": "stderr",
  "logging_pod": "cnpg-cluster-1"
}
```

This check is supposed to fail if there are WALs already present to prevent a WAL archive from containing WAL segments from different clusters - such a WAL archive would not be useful at recovery time.

I wonder if the following WAL archiving errors is related - it could be that PostgreSQL is trying to archive a WAL segment which has the same name as a WAL archived by an earlier instance of the cluster:

```
cnpg-cluster-1 postgres {
  "level": "error",
  "ts": "2023-08-25T15:23:04Z",
  "logger": "wal-archive",
  "msg": "failed to run wal-archive command",
  "logging_pod": "cnpg-cluster-1",
  "error": "unexpected failure invoking barman-cloud-wal-archive: exit status 1",
  "stacktrace": "github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:128\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.NewCmd.func1\n\tinternal/cmd/manager/walarchive/cmd.go:83\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992\nmain.main\n\tcmd/manager/main.go:64\nruntime.main\n\t/opt/hostedtoolcache/go/1.20.3/x64/src/runtime/proc.go:250"
}
```

It's probably worth starting over with an empty bucket at this point and seeing what the logs look like after that.

**Comment by mikewallace1979** [comment]
Excellent news!

**Comment by gaetancollaud** [comment]
For those using Digital Ocean Spaces Object Storage and have the same issue, just configure your bucket like this:

```
      destinationPath: "s3://{BUCKET_NAME}/{FOLDER_NAME}/"
      endpointURL: "https://{REGION}.digitaloceanspaces.com"
```

ex
```
      destinationPath: "s3://backup-test/test-db/"
      endpointURL: "https://fra1.digitaloceanspaces.com"
```
