### ISSUE TITLE
Barman cannot restore to Windows host in most cases

### ISSUE THREAD

**Issue by einhverfr** [EnterpriseDB/barman#896]
Barman can backup a Windows host but restoration is more complicated.  There are several problems here:
1.  Tablespace directories get screwed up because of different path semantics  This is true whether the directories are stored on Linux or on Windows via NFS (the only way of getting around the path semantics issue on restore)
2.  Barman restore assumes the presence of UNIX file and other utilities that do not exist on Windows, including true, mv, and others.

The first would probably be fixed by some sort of normalization of paths before storing tablespaces (or of just handling the differences).  This requires an actual effort to port the application to Windows, though.

**Comment by martinmarques** [comment]
Hi Chris, this seems like a bigger project which is "Support Windows Platform", something that no backup tool that I know of does yet. In our docs, we explicitly mention that you can experimentally backup a Windows Postgres server using the postgres backup_method.

I suggest also using compression so you get tarballs which would remove the issues from (1).

Regarding (2), we don't support recovery, and that's why this is not something we can support fully.

We may at some point think about Windows support, but right now there's not enough traction.
