### ISSUE TITLE
Disable automatic download of partial files with `barman-cloud-wal-restore`

### ISSUE THREAD

**Issue by gbartolini** [EnterpriseDB/barman#928]
Currently, `barman-cloud-wal-restore` automatically downloads a `.partial` file if the requested one is absent. It would be great to introduce an option that disables this behaviour (which I think I introduced).

The option could be `--disable-partial-fallback` or `--strict-name` (`-S`)?.

Note: CloudNativePG needs this feature to provide more control over when the operator can request the download of a partial file.

**Comment by mnencia** [comment]
I don't like `--strict-name` because `barman-cloud-wal-restore` also tries to detect the presence of compressed files by cycling over possible compression extensions, and `--strict-name` would imply to ignore not only the partial file but also the compressed files.

**Comment by martinmarques** [comment]
@mnencia why does `barman-cloud-wal-restore` even try to download a partial WAL file (which I can't find in the code where it does this). This came up here as we are doing some work with the cloud scripts and found this which really doesn't make sense. Can you clarify please?

CC: @gustabowill @barthisrael

**Comment by mnencia** [comment]
Hey @martinmarques, the partial WAL download logic is in [`barman/clients/cloud_walrestore.py`](https://github.com/EnterpriseDB/barman/blob/master/barman/clients/cloud_walrestore.py#L123-L182), in the `CloudWalDownloader.download_wal` method.

It works through `cloud_interface.list_bucket(wal_path)` (line 145), which does a prefix match on the cloud storage path. So when you request e.g. `000000080000ABFF000000C1`, it also returns `000000080000ABFF000000C1.partial` (and any compressed variants). The loop at lines 145-182 iterates over all matches and accepts the first valid candidate — so if the exact WAL file isn't found but a `.partial` version exists in the bucket, it gets downloaded instead.

This exists because during a promotion, `barman-cloud-wal-archive` uploads both the partial WAL from the initial timeline and the complete WAL from the target timeline. If you are trying to recover up to the last transaction on the initial timeline, the partial file is what you need. The `--no-partial` flag was added to close this issue, allowing callers (like CloudNativePG) to opt out of this fallback behavior when they need more control over partial file downloads.
